eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    
spring:
  application:
    admin:
      enabled: true
  sleuth:
    sampler:
      percentage: 1
  zipkin:
    baseUrl: http://ec2-13-229-49-198.ap-southeast-1.compute.amazonaws.com:9411/
  metrics:
    prometheus:
      enabled: true
server:
  port: 8761

logging:
  level:
    org.springframework.cloud.sleuth.log: DEBUG

endpoints:
  shutdown:
    enabled: true
    sensitive: false
  health:
    sensitive: false
management:
  security:
    enabled: false
