spring:
  sleuth:
    sampler:
      percentage: 1
  zipkin:
    baseUrl: http://localhost:9411/
  metrics:
    prometheus:
      enabled: true
  data:
    mongodb:
      host: localhost #mongoserver
      port: 27017

logging:
  level:
    org.springframework.cloud.sleuth.log: DEBUG

endpoints:
  shutdown:
    enabled: true
    sensitive: false
  health:
    sensitive: false
management:
  security:
    enabled: false

